### ISSUE TITLE
Change module name to googleapis.sheets

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/module-ballerinax-googleapis.sheets#115]
**Description:**
As we planned to remove API version from the module name, we need to change the module name of this connector to `googleapis.sheets`

**Comment by LakshanSS** [comment]
This issue can be closed since it is done
https://github.com/ballerina-platform/module-ballerinax-googleapis.sheets/blob/1e684b02bbbd5815d31ade9afeef75ad7964e07d/gsheet/Ballerina.toml#L3

**Comment by RolandHewage** [comment]
This is already done in https://github.com/ballerina-platform/module-ballerinax-googleapis.sheets/blob/1e684b02bbbd5815d31ade9afeef75ad7964e07d/gsheet/Ballerina.toml#L3
Therefore closing this issue.
