### ISSUE TITLE
Need to add this configuration step in the `Obtaining Tokens`

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [ballerina-platform/module-ballerinax-googleapis.sheets#166]
**Description:**
The following playground configurations should be included under the `Obtaining Tokens` in the `README` and `Module` files. Otherwise, we can't get the token for created clent_id and client_secret.
<img width="840" alt="Screenshot 2021-06-18 at 5 55 06 PM" src="https://user-images.githubusercontent.com/12771261/122560957-ddb40d80-d05e-11eb-8f52-860f2fbe1e31.png">

**Comment by LakshanSS** [comment]
@RolandHewage

**Comment by abeykoon** [comment]
In the common format of documentation, we pointed to [1]. But can be seen as an improvement. 

[1]. https://developers.google.com/identity/protocols/oauth2

**Comment by abeykoon** [comment]
Moved to https://github.com/ballerina-platform/ballerina-extended-library/issues/48
