### ISSUE TITLE
Error thrown when sheet name has spaces

### ISSUE THREAD

**Issue by arunans23** [ballerina-platform/module-ballerinax-googleapis.sheets#47]
**Description:**

> getCellData(string spreadsheetId, string sheetName, string column, int row) returns (string | error<>)

When trying to get cell values out of the spreadsheet, the arguments has a field called 'sheetName'. In google's point of view, we can have spaces in the sheet name. But in this module, if a space is passed in this field (eg: 'form responses'), the following error is thrown.

`(wso2/gsheets4)SpreadsheetError {"message":"Error occurred while accessing the JSON payload of the response"}`

My thinking is that, when calling google API, the 'sheet name' is not properly encoded, hence the response does not have a proper json. This problem is there for all the endpoints which uses sheetName.

**Suggested Labels:**
Bug

**Suggested Assignees:**

**Affected Product Version:**
gsheet4 - v0.8.20
ballerina - v0.990.2

**OS, DB, other environment details and versions:**    
MacOS

**Steps to reproduce:**

**Related Issues:**

**Comment by arunans23** [comment]
Found this [here](https://developers.google.com/sheets/api/guides/concepts).

> If the sheet name has spaces or starts with a bracket, surround the sheet name with single quotes ('), e.g 'Sheet One'!A1:B2. For simplicity, it is safe to always surround the sheet name with single quotes.

**Comment by RolandHewage** [comment]
This is an outdated issue. The `getCelldata` operation is replaced by `getCell` operation here
https://github.com/ballerina-platform/module-ballerinax-googleapis.sheets/blob/master/gsheet/client.bal#L1076

The above scenario is working fine now in the current implementation
![Screenshot from 2021-09-17 13-23-32](https://user-images.githubusercontent.com/44081958/133746078-b2302f4d-8a99-49d3-9b94-d6bdfcd202ff.png)

Therefore closing this issue.
