### ISSUE TITLE
Automate connector testing

### ISSUE THREAD

**Issue by MalshaL** [ballerina-platform/module-ballerinax-googleapis.sheets#63]
**Description:**
Implement automated testing for connector by adding to test grid.

**Suggested Labels:**
Type/Task

**Comment by LakshanSS** [comment]
Can close this since tests are added for all the operations

**Comment by LakshanSS** [comment]
@RolandHewage Can u verify and close the issue?

**Comment by RolandHewage** [comment]
Automated testing for the connector is already implemented here
https://github.com/ballerina-platform/module-ballerinax-googleapis.sheets/blob/master/gsheet/tests/test.bal
Therefore closing this issue.
